/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  UseRandom,
  UseRandomInterface,
} from "../../../contracts/gamification/UseRandom";

const _abi = [
  {
    inputs: [],
    name: "ITERATIONS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PRIME",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class UseRandom__factory {
  static readonly abi = _abi;
  static createInterface(): UseRandomInterface {
    return new utils.Interface(_abi) as UseRandomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UseRandom {
    return new Contract(address, _abi, signerOrProvider) as UseRandom;
  }
}
