/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as depositHelperErc4626Sol from "./DepositHelperERC4626.sol";
export type { depositHelperErc4626Sol };
import type * as depositHelperReaperBptSol from "./DepositHelperReaperBPT.sol";
export type { depositHelperReaperBptSol };
