/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEmissionCurve,
  IEmissionCurveInterface,
} from "../../../contracts/interfaces/IEmissionCurve";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "lastRewardTime",
        type: "uint256",
      },
    ],
    name: "getRate",
    outputs: [
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEmissionCurve__factory {
  static readonly abi = _abi;
  static createInterface(): IEmissionCurveInterface {
    return new utils.Interface(_abi) as IEmissionCurveInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEmissionCurve {
    return new Contract(address, _abi, signerOrProvider) as IEmissionCurve;
  }
}
