/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  INFTDescriptor,
  INFTDescriptorInterface,
} from "../../../contracts/interfaces/INFTDescriptor";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "relicId",
        type: "uint256",
      },
    ],
    name: "constructTokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class INFTDescriptor__factory {
  static readonly abi = _abi;
  static createInterface(): INFTDescriptorInterface {
    return new utils.Interface(_abi) as INFTDescriptorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTDescriptor {
    return new Contract(address, _abi, signerOrProvider) as INFTDescriptor;
  }
}
