/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChildRewarder } from "./ChildRewarder";
export type { DepositBonusRewarder } from "./DepositBonusRewarder";
export type { MultiplierRewarder } from "./MultiplierRewarder";
export type { MultiplierRewarderOwnable } from "./MultiplierRewarderOwnable";
export type { ParentRewarder } from "./ParentRewarder";
export type { SingleAssetRewarder } from "./SingleAssetRewarder";
